name: Sapper Publish

on:
  push:
    branches:
      - develop

jobs:
  export-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Sapper to GitHub Pages
        uses: antoncarlsson/deploy-sapper-to-gh-pages-action@v1.1.2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
