name: Sapper Publish

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Deploy Sapper to GitHub Pages
        uses: antoncarlsson/deploy-sapper-to-gh-pages-action@v1.1.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
